DECLARE
    EMP_ID NUMBER := 719;
    EMP_NAME VARCHAR2(25) := 'Vishesh';
    BASIC_SALARY NUMBER := 148000;
    HRA_AMOUNT NUMBER;

BEGIN
    HRA_AMOUNT := BASIC_SALARY * 0.40;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: ' || EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: ' || EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('BASIC SALARY: RS. ' || BASIC_SALARY);
    DBMS_OUTPUT.PUT_LINE('HOUSE RENT ALLOWANCE: RS. ' || HRA_AMOUNT);

    IF BASIC_SALARY > 60000 THEN
        DBMS_OUTPUT.PUT_LINE('TAX APPLICABLE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('TAX NOT APPLICABLE');
    END IF;

END;